=== Artm-hv/WIKAREK_Aplikacje_internetowe/03-Kody_wyklady/19 - XML/03 - Normalizacja/n.dtd
<!ENTITY  ucz  SYSTEM "n1.xml">
<!ENTITY  zaw  SYSTEM "n2.xml">
<!ENTITY % ucz_d  SYSTEM "n1.dtd">
<!ENTITY % zaw_d  SYSTEM "n2.dtd">
%ucz_d;
%zaw_d;
<!ELEMENT zloto (#PCDATA)>
<!ELEMENT srebro (#PCDATA)>
<!ELEMENT braz (#PCDATA)>
<!ELEMENT wynik (zloto,srebro,braz)>
<!ELEMENT igrzyskaOlimpijskie (Uczestnicy,Zawody,wynik+)>
<!ATTLIST igrzyskaOlimpijskie miasto CDATA #REQUIRED>
<!ATTLIST igrzyskaOlimpijskie rok CDATA #REQUIRED>
<!ATTLIST zloto idz IDREF #REQUIRED>
<!ATTLIST zloto idk IDREF #REQUIRED>
<!ATTLIST srebro idz IDREF #REQUIRED>
<!ATTLIST srebro idk IDREF #REQUIRED>
<!ATTLIST braz idz IDREF #REQUIRED>
<!ATTLIST braz idk IDREF #REQUIRED>

=== Artm-hv/WIKAREK_Aplikacje_internetowe/03-Kody_wyklady/19 - XML/03 - Normalizacja/n.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE igrzyskaOlimpijskie SYSTEM "n.dtd"> 
<igrzyskaOlimpijskie miasto="Ateny" rok="2004">
 &ucz;
 &zaw;
 <wynik>
  <zloto  idz="Z01" idk="K01">20,3</zloto>
  <srebro idz="Z01" idk="K01">30,4</srebro>
  <braz   idz="Z01" idk="K01">40,3</braz>
 </wynik>
 <wynik>
  <zloto  idz="Z03" idk="K02">20,3</zloto>
  <srebro idz="Z04" idk="K02">30,4</srebro>
  <braz   idz="Z05" idk="K02">40,3</braz>
 </wynik>
 <wynik>
  <zloto  idz="Z06" idk="K03">20,3</zloto>
  <srebro idz="Z01" idk="K03">30,4</srebro>
  <braz   idz="Z02" idk="K03">40,3</braz>
 </wynik>
 <wynik>
  <zloto  idz="Z01" idk="K04">20,3</zloto>
  <srebro idz="Z02" idk="K04">30,4</srebro>
  <braz   idz="Z02" idk="K04">40,3</braz>
 </wynik>
</igrzyskaOlimpijskie>
